### ISSUE TITLE
Rescale exptime on longexposure change

### ISSUE THREAD

**Issue by scizen9** [CaltechOpticalObservatories/camera-interface-v1#19]
If longexposure is false (0) and you set an exptime of 2000 (2s) then issue longexposure 1, the exptime will stay at 2000.  It should be rescaled according to the current state of longexposure.

**Comment by scizen9** [comment]
Dave points out that if you set an exptime while in ms mode and that exptime does not convert to an integer second, it might be a problem.  For example, converting 1500 ms to 1 s will be inaccurate.  Both modes expect integer values.  Consider always using ms internally, but accepting both ms or s input exposure times?

**Comment by astronomerdave** [comment]
How about a configurable exposure time unit? Some instruments I know will use seconds while others I know will use msec (NGPS uses sec and NIRC2 uses msec). Currently, those two instruments are using their own special camerad. For camerad to be universal, a configurable exposure time unit might be justified. It's not something one ever wants to think about or script nightly, so once it's configured then it's done.

A configurable time unit would not preclude the use of the `longexposure` command, but I think that situation is only going to occur for lab testing/development. The _only_ use case for longexposure is when you need exposure times greater than 34 minutes and when thinking of exposure times in tens of minutes, I think no one would be wanting to supply all the digits for milliseconds, nor require a exposure resolution of milliseconds.

As I noted in my comment on one of the PRs, one can always send `exptime` to return the current exposure time with its unit.

Incidentally, the reason behind `longexposure` was Tim needed to take long (multi-hour) exposures for measuring dark current, something not routinely done. But the Archon parameters are 20 bits, so the longest exposure delay is `0x1FFFFF`. That value represented in msec equates to 34.95 minutes, so he re-defined the unit in his ACF in order to accommodate hour-long exposures (at the cost of resolution).

**Comment by scizen9** [comment]
If the only reasonable choices are seconds or milliseconds, why not make it configuration parameter?  I doubt one would not know what scale you wanted before you started camerad.  If you wanted the other, just exit and edit the config file.

**Comment by scizen9** [comment]
Closing this issue as we are converging on making the exptime units a config parameter.
