### ISSUE TITLE
DIN_PORT Error

### ISSUE THREAD

**Issue by scizen9** [CaltechOpticalObservatories/camera-interface-v1#37]
When using camerad this error occasionally shows up when:
telnet to camerad port: 'telnet localhost 3031',
then issue open command.  The text of the error message is:

``(Archon::Interface::fetchlog) 00000000494283230213: Unknown instruction on line 11 ("DIN_PORT") [vcpu_compile:641]``

It is usually issued several times in a row (~4), but sometimes only once and sometimes not at all.

An examination of the ACF files shows the lines referenced in the error to be correct:

MOD10\VCPU_LINE10=";" 
MOD10\VCPU_LINE11="DIN_PORT=0x0000                   ; digital input port register"
MOD10\VCPU_LINE12="SOFT_TRIG=0x0010                  ; software trigger VCPU_INREG0"

An example in the documentation for the Archon matches the line referenced.

**Comment by astronomerdave** [comment]
Try reading back the config after writing it, to see if something got changed unexpectedly. One could do this from the command line with native commands but might be tedious; how about I write a test function to do this?

**Comment by astronomerdave** [comment]
Okay, I whipped up a couple of new commands in the test function (`test <cmd> <arg> ...`) that might help debug this. This will save you from having to figure out all the line numbers in hex and issue individual RCONFIG commands. I use test so that I don't have to make a separate command in the main server for every odd little thing, especially engineering commands.

The commands are:

```
   test logwconfig [ true | false ]
   test rconfig [ line | mod | param | state | vcpu ]
   test rconfigmap [ line | mod | param | state | vcpu ]
```

If you set **logwconfig** true, then load an ACF, it will log all the WCONFIG commands (which are normally not logged).

`rconfig [ <arg> ]` will read back the configuration directly from Archon (using **RCONFIGxxxx**). With no args it reads (and logs) the complete configuration. If you pass an optional argument (line, mod, etc.) then it will filter out only those configuration lines of that type. I.E. if you want to see only the VCPU configuration lines, use `rconfig vcpu`. This way you can see if the Archon has something different stored than what you think should be there.

When you load an ACF from disk, in addition to writing it to Archon, a copy is kept in host memory (in a map). **rconfigmap** works similar to **rconfig**, except instead of making calls to Archon it reports what's in the map, which is what it read from the ACF file and what it _thinks_ should have been written to Archon. So you can look for discrepancies.

This is on PR #39

**Comment by astronomerdave** [comment]
PR #39 now solves this issue.
